### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vincelessard** [BIO6032/2018_replication_hassell_1985#1]
### General
- [x] Read introduction to `git` @BIO6032/cours2018 #5 
- [x] Read a few [ReScience papers](https://rescience.github.io/read/) @BIO6032/cours2018 

### Model
- [x] Create conceptual model
   - [x] box model (parameters, variables, equations) @QileWu 
   - [x] create file for functions #2
- [x] prepare/write functions 
   - [x] list functions #3 
   - [x] write base script for functions #4 

### Paper
- [x]  Outline
   - [x] Intro @DominiqueCaron #9 
   - [x] Method @vincelessard #9

### Model
- [x] Add documentation for functions #4 
- [x] Add function k-value

### Paper
- [x] Outline
  - [x] Results (Description of each figures)
- [x] Draft #14 
  -  [x] Paragraph 1 introduction
  -  [x] Paragraph 1 method

### Figures
- [x] List and describe figures with the parameters used #12 
- [x] Create file for figures
- [x] replication FIG. 3 from Hassel)
  - [x] FIG 3(a)
  - [x] FIG 3(b)
  - [x] FIG 3(c)
  - [x] FIG 3(d)

### Model
- [x] Try to include stochasticity to the model for Fig5 and Fig6

### Paper
- [x] Draft #14 
  - [x] Finish introduction
  - [x] Finish method
- [x] Explore original paper impacts in population dynamics #20

### Figures
- [x] Create Figure 4
  - [x] Fig 4a
  - [x] Fig 4b

### Model
- [x] Figure out how to include stochasticity for Figure 5a-c and Figure 6a-c

### Paper
- [x] Start writing results for Figures 3 and 4

### Figures
- [x] Create Figures 5 and 6

### Paper

- [x] Write caption for the figures @vincelessard 
   - [x] Figure 3
   - [x] Figure 4
   - [x] Figure 5
   - [x] Figure 6
   - [x] Figure 7
   - [x] Figure 8
- [x] Update references in the ReScience markdown document @QileWu 
### Figures
- [x] Create Figure 7 (changes in the correlation when stochasticity is included in the model - specialist) @DominiqueCaron 
- [x] Update Figure 5 @DominiqueCaron 
- [x] Create Figure 8 (changes in the correlation when stochasticity is included in the model - generalist) @DominiqueCaron 

### Paper
- [x] Delete Eq5 and add a new equation for S (S=f(N,T)*N) @vincelessard 
- [x] Rearrange figure captions @vincelessard 
- [x] Write results for stochastic model --> Figures 5, 6, 7 (include changes in the coding when including stochasticity) @vincelessard 
- [x] Continue writing discussion @DominiqueCaron 
- [x] Write conclusion @QileWu 
- [x] Complete bibliography @QileWu 

### Figures
- [x] Include annotations in Fig7 and Fig8 to indicate which parameter is treated as a stochastic variable @DominiqueCaron

**Comment by tpoisot** [comment]
**Info**: you can mention issues in your commit messages: `add a function for growth rate (#3)` would make the commit appear in issue 3 (for example).
